#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
examples_dir="$(cd -- "${script_dir}/.." && pwd)"

venv="${ROCFUZZ_THEROCK_VENV:-${examples_dir}/.venv}"
python="${PYTHON:-python3.12}"
index_url="${ROCFUZZ_THEROCK_INDEX:-https://rocm.nightlies.amd.com/whl-multi-arch/}"
devices="${ROCFUZZ_THEROCK_DEVICES:-gfx1201,gfx1100}"
version="${ROCFUZZ_THEROCK_VERSION:-}"

if ! command -v uv >/dev/null 2>&1; then
    echo "error: uv is required on PATH" >&2
    exit 1
fi

uv venv "${venv}" --python "${python}" --allow-existing

extras="devel,libraries"
device_packages=()
IFS=',' read -r -a device_list <<< "${devices}"
for device in "${device_list[@]}"; do
    device="${device//[[:space:]]/}"
    if [[ -n "${device}" ]]; then
        extras+=",device-${device}"
        if [[ "${device}" != "all" ]]; then
            device_packages+=("rocm-sdk-device-${device}")
        fi
    fi
done

rocm_package="rocm[${extras}]"
devel_package="rocm-sdk-devel"
if [[ -n "${version}" ]]; then
    rocm_package+="==${version}"
    devel_package+="==${version}"
fi

uv pip install \
    --python "${venv}/bin/python" \
    --index-url "${index_url}" \
    "${rocm_package}" \
    "${devel_package}" \
    "${device_packages[@]}"

rocm_sdk="${venv}/bin/rocm-sdk"
rocm_root="$("${rocm_sdk}" path --root)"
cmake_prefix="$("${rocm_sdk}" path --cmake)"
bin_path="$("${rocm_sdk}" path --bin)"
sdk_version="$("${rocm_sdk}" version)"
sdk_targets="$("${rocm_sdk}" targets)"
libraries_root="$("${venv}/bin/python" - <<'PY'
import importlib.util
import pathlib

spec = importlib.util.find_spec("_rocm_sdk_libraries")
if spec and spec.submodule_search_locations:
    print(pathlib.Path(spec.submodule_search_locations[0]))
PY
)"
if [[ -z "${libraries_root}" ]]; then
    libraries_root="${rocm_root}"
fi

cat > "${examples_dir}/therock.env" <<EOF
# Generated by scripts/setup-therock.sh.
export ROCFUZZ_THEROCK_VENV="${venv}"
export ROCFUZZ_THEROCK_ROOT="${rocm_root}"
export ROCFUZZ_THEROCK_LIBRARIES_ROOT="${libraries_root}"
export ROCFUZZ_THEROCK_CMAKE_PREFIX="${cmake_prefix}"
export ROCFUZZ_THEROCK_VERSION="${sdk_version}"
export ROCM_PATH="${rocm_root}"
export CMAKE_PREFIX_PATH="${cmake_prefix}:\${CMAKE_PREFIX_PATH:-}"
export LD_LIBRARY_PATH="${libraries_root}/lib:${rocm_root}/lib:\${LD_LIBRARY_PATH:-}"
export ROCBLAS_TENSILE_LIBPATH="${libraries_root}/lib/rocblas/library"
export HIPBLASLT_TENSILE_LIBPATH="${libraries_root}/lib/hipblaslt/library"
export PATH="${bin_path}:${venv}/bin:\${PATH}"
EOF

cat <<EOF
TheRock ROCm SDK ${sdk_version}
  root:      ${rocm_root}
  libraries: ${libraries_root}
  cmake:     ${cmake_prefix}
  targets:   ${sdk_targets}

Wrote ${examples_dir}/therock.env
EOF
